# 01 Data Validation & Import

## Goal

Validate the structure of the weekly UK Top 100 chart dataset before importing it into the project database.

### Tasks

- Verify sheet names
- Verify chart format
- Verify column names
- Verify data types
- Import all weekly charts from 1983 onwards

In [1]:
from pathlib import Path

In [2]:
project_path = Path.cwd().parent
project_path

WindowsPath('c:/Users/sabur/Desktop/what-happened-to-music')

In [3]:
raw_path = project_path / "data" / "raw"
raw_path

WindowsPath('c:/Users/sabur/Desktop/what-happened-to-music/data/raw')

In [4]:
chart_file = raw_path / "top_100_songs_1952_to_2024.xlsx"

chart_file

WindowsPath('c:/Users/sabur/Desktop/what-happened-to-music/data/raw/top_100_songs_1952_to_2024.xlsx')

In [6]:
import pandas as pd
excel = pd.ExcelFile(chart_file)

In [7]:
excel.sheet_names

['Week 19521114',
 'Week 19521121',
 'Week 19521128',
 'Week 19521205',
 'Week 19521212',
 'Week 19521219',
 'Week 19521226',
 'Week 19530102',
 'Week 19530109',
 'Week 19530116',
 'Week 19530123',
 'Week 19530130',
 'Week 19530206',
 'Week 19530213',
 'Week 19530220',
 'Week 19530227',
 'Week 19530306',
 'Week 19530313',
 'Week 19530320',
 'Week 19530327',
 'Week 19530403',
 'Week 19530410',
 'Week 19530417',
 'Week 19530424',
 'Week 19530501',
 'Week 19530508',
 'Week 19530515',
 'Week 19530522',
 'Week 19530529',
 'Week 19530605',
 'Week 19530612',
 'Week 19530619',
 'Week 19530626',
 'Week 19530703',
 'Week 19530710',
 'Week 19530717',
 'Week 19530724',
 'Week 19530731',
 'Week 19530807',
 'Week 19530814',
 'Week 19530821',
 'Week 19530828',
 'Week 19530904',
 'Week 19530911',
 'Week 19530918',
 'Week 19530925',
 'Week 19531002',
 'Week 19531009',
 'Week 19531016',
 'Week 19531023',
 'Week 19531030',
 'Week 19531106',
 'Week 19531113',
 'Week 19531120',
 'Week 19531127',
 'Week 19531204',
 'Week 19531211',
 'Week 19531218',
 'Week 19531225',
 'Week 19540101',
 'Week 19540108',
 'Week 19540115',
 'Week 19540122',
 'Week 19540129',
 'Week 19540205',
 'Week 19540212',
 'Week 19540219',
 'Week 19540226',
 'Week 19540305',
 'Week 19540312',
 'Week 19540319',
 'Week 19540326',
 'Week 19540402',
 'Week 19540409',
 'Week 19540416',
 'Week 19540423',
 'Week 19540430',
 'Week 19540507',
 'Week 19540514',
 'Week 19540521',
 'Week 19540528',
 'Week 19540604',
 'Week 19540611',
 'Week 19540618',
 'Week 19540625',
 'Week 19540702',
 'Week 19540709',
 'Week 19540716',
 'Week 19540723',
 'Week 19540730',
 'Week 19540806',
 'Week 19540813',
 'Week 19540820',
 'Week 19540827',
 'Week 19540903',
 'Week 19540910',
 'Week 19540917',
 'Week 19540924',
 'Week 19541001',
 'Week 19541008',
 'Week 19541015',
 'Week 19541022',
 'Week 19541029',
 'Week 19541105',
 'Week 19541112',
 'Week 19541119',
 'Week 19541126',
 'Week 19541203',
 'Week 19541210',
 'Week 19541217',
 'Week 19541224',
 'Week 19541231',
 'Week 19550107',
 'Week 19550114',
 'Week 19550121',
 'Week 19550128',
 'Week 19550204',
 'Week 19550211',
 'Week 19550218',
 'Week 19550225',
 'Week 19550304',
 'Week 19550311',
 'Week 19550318',
 'Week 19550325',
 'Week 19550401',
 'Week 19550408',
 'Week 19550415',
 'Week 19550422',
 'Week 19550429',
 'Week 19550506',
 'Week 19550513',
 'Week 19550520',
 'Week 19550527',
 'Week 19550603',
 'Week 19550610',
 'Week 19550617',
 'Week 19550624',
 'Week 19550701',
 'Week 19550708',
 'Week 19550715',
 'Week 19550722',
 'Week 19550729',
 'Week 19550805',
 'Week 19550812',
 'Week 19550819',
 'Week 19550826',
 'Week 19550902',
 'Week 19550909',
 'Week 19550916',
 'Week 19550923',
 'Week 19550930',
 'Week 19551007',
 'Week 19551014',
 'Week 19551021',
 'Week 19551028',
 'Week 19551104',
 'Week 19551111',
 'Week 19551118',
 'Week 19551125',
 'Week 19551202',
 'Week 19551209',
 'Week 19551216',
 'Week 19551223',
 'Week 19551230',
 'Week 19560106',
 'Week 19560113',
 'Week 19560120',
 'Week 19560127',
 'Week 19560203',
 'Week 19560210',
 'Week 19560217',
 'Week 19560224',
 'Week 19560302',
 'Week 19560309',
 'Week 19560316',
 'Week 19560323',
 'Week 19560330',
 'Week 19560406',
 'Week 19560413',
 'Week 19560420',
 'Week 19560427',
 'Week 19560504',
 'Week 19560511',
 'Week 19560518',
 'Week 19560525',
 'Week 19560601',
 'Week 19560608',
 'Week 19560615',
 'Week 19560622',
 'Week 19560629',
 'Week 19560706',
 'Week 19560713',
 'Week 19560720',
 'Week 19560727',
 'Week 19560803',
 'Week 19560810',
 'Week 19560817',
 'Week 19560824',
 'Week 19560831',
 'Week 19560907',
 'Week 19560914',
 'Week 19560921',
 'Week 19560928',
 'Week 19561005',
 'Week 19561012',
 'Week 19561019',
 'Week 19561026',
 'Week 19561102',
 'Week 19561109',
 'Week 19561116',
 'Week 19561123',
 'Week 19561130',
 'Week 19561207',
 'Week 19561214',
 'Week 19561221',
 'Week 19561228',
 'Week 19570104',
 'Week 19570111',
 'Week 19570118',
 'Week 19570125',
 'Week 19570201',
 'Week 19570208',
 'Week 19570215',
 'Week 19570222',
 'Week 19570301',
 'Week 19570308',
 'Week 19570315',
 'Week 19570322',
 'Week 19570329',
 'Week 19570405',
 'Week 19570412',
 'Week 19570419',
 'Week 19570426',
 'Week 19570503',
 'Week 19570510',
 'Week 19570517',
 'Week 19570524',
 'Week 19570531',
 'Week 19570607',
 'Week 19570614',
 'Week 19570621',
 'Week 19570628',
 'Week 19570705',
 'Week 19570712',
 'Week 19570719',
 'Week 19570726',
 'Week 19570802',
 'Week 19570809',
 'Week 19570816',
 'Week 19570823',
 'Week 19570830',
 'Week 19570906',
 'Week 19570913',
 'Week 19570920',
 'Week 19570927',
 'Week 19571004',
 'Week 19571011',
 'Week 19571018',
 'Week 19571025',
 'Week 19571101',
 'Week 19571108',
 'Week 19571115',
 'Week 19571122',
 'Week 19571129',
 'Week 19571206',
 'Week 19571213',
 'Week 19571220',
 'Week 19571227',
 'Week 19580103',
 'Week 19580110',
 'Week 19580117',
 'Week 19580124',
 'Week 19580131',
 'Week 19580207',
 'Week 19580214',
 'Week 19580221',
 'Week 19580228',
 'Week 19580307',
 'Week 19580314',
 'Week 19580321',
 'Week 19580328',
 'Week 19580404',
 'Week 19580411',
 'Week 19580418',
 'Week 19580425',
 'Week 19580502',
 'Week 19580509',
 'Week 19580516',
 'Week 19580523',
 'Week 19580530',
 'Week 19580606',
 'Week 19580613',
 'Week 19580620',
 'Week 19580627',
 'Week 19580704',
 'Week 19580711',
 'Week 19580718',
 'Week 19580725',
 'Week 19580801',
 'Week 19580808',
 'Week 19580815',
 'Week 19580822',
 'Week 19580829',
 'Week 19580905',
 'Week 19580912',
 'Week 19580919',
 'Week 19580926',
 'Week 19581003',
 'Week 19581010',
 'Week 19581017',
 'Week 19581024',
 'Week 19581031',
 'Week 19581107',
 'Week 19581114',
 'Week 19581121',
 'Week 19581128',
 'Week 19581205',
 'Week 19581212',
 'Week 19581219',
 'Week 19581226',
 'Week 19590102',
 'Week 19590109',
 'Week 19590116',
 'Week 19590123',
 'Week 19590130',
 'Week 19590206',
 'Week 19590213',
 'Week 19590220',
 'Week 19590227',
 'Week 19590306',
 'Week 19590313',
 'Week 19590320',
 'Week 19590327',
 'Week 19590403',
 'Week 19590410',
 'Week 19590417',
 'Week 19590424',
 'Week 19590501',
 'Week 19590508',
 'Week 19590515',
 'Week 19590522',
 'Week 19590529',
 'Week 19590605',
 'Week 19590612',
 'Week 19590619',
 'Week 19590626',
 'Week 19590703',
 'Week 19590710',
 'Week 19590717',
 'Week 19590724',
 'Week 19590731',
 'Week 19590807',
 'Week 19590814',
 'Week 19590821',
 'Week 19590828',
 'Week 19590904',
 'Week 19590911',
 'Week 19590918',
 'Week 19590925',
 'Week 19591002',
 'Week 19591009',
 'Week 19591016',
 'Week 19591023',
 'Week 19591030',
 'Week 19591106',
 'Week 19591113',
 'Week 19591120',
 'Week 19591127',
 'Week 19591204',
 'Week 19591211',
 'Week 19591218',
 'Week 19591225',
 'Week 19600101',
 'Week 19600108',
 'Week 19600115',
 'Week 19600122',
 'Week 19600129',
 'Week 19600205',
 'Week 19600212',
 'Week 19600219',
 'Week 19600226',
 'Week 19600304',
 'Week 19600311',
 'Week 19600318',
 'Week 19600325',
 'Week 19600401',
 'Week 19600408',
 'Week 19600415',
 'Week 19600422',
 'Week 19600429',
 'Week 19600506',
 'Week 19600513',
 'Week 19600520',
 'Week 19600527',
 'Week 19600603',
 'Week 19600610',
 'Week 19600617',
 'Week 19600624',
 'Week 19600701',
 'Week 19600708',
 'Week 19600715',
 'Week 19600722',
 'Week 19600729',
 'Week 19600805',
 'Week 19600812',
 'Week 19600819',
 'Week 19600826',
 'Week 19600902',
 'Week 19600909',
 'Week 19600916',
 'Week 19600923',
 'Week 19600930',
 'Week 19601007',
 'Week 19601014',
 'Week 19601021',
 'Week 19601028',
 'Week 19601104',
 'Week 19601111',
 'Week 19601118',
 'Week 19601125',
 'Week 19601202',
 'Week 19601209',
 'Week 19601216',
 'Week 19601223',
 'Week 19601230',
 'Week 19610106',
 'Week 19610113',
 'Week 19610120',
 'Week 19610127',
 'Week 19610203',
 'Week 19610210',
 'Week 19610217',
 'Week 19610224',
 'Week 19610303',
 'Week 19610310',
 'Week 19610317',
 'Week 19610324',
 'Week 19610331',
 'Week 19610407',
 'Week 19610414',
 'Week 19610421',
 'Week 19610428',
 'Week 19610505',
 'Week 19610512',
 'Week 19610519',
 'Week 19610526',
 'Week 19610602',
 'Week 19610609',
 'Week 19610616',
 'Week 19610623',
 'Week 19610630',
 'Week 19610707',
 'Week 19610714',
 'Week 19610721',
 'Week 19610728',
 'Week 19610804',
 'Week 19610811',
 'Week 19610818',
 'Week 19610825',
 'Week 19610901',
 'Week 19610908',
 'Week 19610915',
 'Week 19610922',
 'Week 19610929',
 'Week 19611006',
 'Week 19611013',
 'Week 19611020',
 'Week 19611027',
 'Week 19611103',
 'Week 19611110',
 'Week 19611117',
 'Week 19611124',
 'Week 19611201',
 'Week 19611208',
 'Week 19611215',
 'Week 19611222',
 'Week 19611229',
 'Week 19620105',
 'Week 19620112',
 'Week 19620119',
 'Week 19620126',
 'Week 19620202',
 'Week 19620209',
 'Week 19620216',
 'Week 19620223',
 'Week 19620302',
 'Week 19620309',
 'Week 19620316',
 'Week 19620323',
 'Week 19620330',
 'Week 19620406',
 'Week 19620413',
 'Week 19620420',
 'Week 19620427',
 'Week 19620504',
 'Week 19620511',
 'Week 19620518',
 'Week 19620525',
 'Week 19620601',
 'Week 19620608',
 'Week 19620615',
 'Week 19620622',
 'Week 19620629',
 'Week 19620706',
 'Week 19620713',
 'Week 19620720',
 'Week 19620727',
 'Week 19620803',
 'Week 19620810',
 'Week 19620817',
 'Week 19620824',
 'Week 19620831',
 'Week 19620907',
 'Week 19620914',
 'Week 19620921',
 'Week 19620928',
 'Week 19621005',
 'Week 19621012',
 'Week 19621019',
 'Week 19621026',
 'Week 19621102',
 'Week 19621109',
 'Week 19621116',
 'Week 19621123',
 'Week 19621130',
 'Week 19621207',
 'Week 19621214',
 'Week 19621221',
 'Week 19621228',
 'Week 19630104',
 'Week 19630111',
 'Week 19630118',
 'Week 19630125',
 'Week 19630201',
 'Week 19630208',
 'Week 19630215',
 'Week 19630222',
 'Week 19630301',
 'Week 19630308',
 'Week 19630315',
 'Week 19630322',
 'Week 19630329',
 'Week 19630405',
 'Week 19630412',
 'Week 19630419',
 'Week 19630426',
 'Week 19630503',
 'Week 19630510',
 'Week 19630517',
 'Week 19630524',
 'Week 19630531',
 'Week 19630607',
 'Week 19630614',
 'Week 19630621',
 'Week 19630628',
 'Week 19630705',
 'Week 19630712',
 'Week 19630719',
 'Week 19630726',
 'Week 19630802',
 'Week 19630809',
 'Week 19630816',
 'Week 19630823',
 'Week 19630830',
 'Week 19630906',
 'Week 19630913',
 'Week 19630920',
 'Week 19630927',
 'Week 19631004',
 'Week 19631011',
 'Week 19631018',
 'Week 19631025',
 'Week 19631101',
 'Week 19631108',
 'Week 19631115',
 'Week 19631122',
 'Week 19631129',
 'Week 19631206',
 'Week 19631213',
 'Week 19631220',
 'Week 19631227',
 'Week 19640103',
 'Week 19640110',
 'Week 19640117',
 'Week 19640124',
 'Week 19640131',
 'Week 19640207',
 'Week 19640214',
 'Week 19640221',
 'Week 19640228',
 'Week 19640306',
 'Week 19640313',
 'Week 19640320',
 'Week 19640327',
 'Week 19640403',
 'Week 19640410',
 'Week 19640417',
 'Week 19640424',
 'Week 19640501',
 'Week 19640508',
 'Week 19640515',
 'Week 19640522',
 'Week 19640529',
 'Week 19640605',
 'Week 19640612',
 'Week 19640619',
 'Week 19640626',
 'Week 19640703',
 'Week 19640710',
 'Week 19640717',
 'Week 19640724',
 'Week 19640731',
 'Week 19640807',
 'Week 19640814',
 'Week 19640821',
 'Week 19640828',
 'Week 19640904',
 'Week 19640911',
 'Week 19640918',
 'Week 19640925',
 'Week 19641002',
 'Week 19641009',
 'Week 19641016',
 'Week 19641023',
 'Week 19641030',
 'Week 19641106',
 'Week 19641113',
 'Week 19641120',
 'Week 19641127',
 'Week 19641204',
 'Week 19641211',
 'Week 19641218',
 'Week 19641225',
 'Week 19650101',
 'Week 19650108',
 'Week 19650115',
 'Week 19650122',
 'Week 19650129',
 'Week 19650205',
 'Week 19650212',
 'Week 19650219',
 'Week 19650226',
 'Week 19650305',
 'Week 19650312',
 'Week 19650319',
 'Week 19650326',
 'Week 19650402',
 'Week 19650409',
 'Week 19650416',
 'Week 19650423',
 'Week 19650430',
 'Week 19650507',
 'Week 19650514',
 'Week 19650521',
 'Week 19650528',
 'Week 19650604',
 'Week 19650611',
 'Week 19650618',
 'Week 19650625',
 'Week 19650702',
 'Week 19650709',
 'Week 19650716',
 'Week 19650723',
 'Week 19650730',
 'Week 19650806',
 'Week 19650813',
 'Week 19650820',
 'Week 19650827',
 'Week 19650903',
 'Week 19650910',
 'Week 19650917',
 'Week 19650924',
 'Week 19651001',
 'Week 19651008',
 'Week 19651015',
 'Week 19651022',
 'Week 19651029',
 'Week 19651105',
 'Week 19651112',
 'Week 19651119',
 'Week 19651126',
 'Week 19651203',
 'Week 19651210',
 'Week 19651217',
 'Week 19651224',
 'Week 19651231',
 'Week 19660107',
 'Week 19660114',
 'Week 19660121',
 'Week 19660128',
 'Week 19660204',
 'Week 19660211',
 'Week 19660218',
 'Week 19660225',
 'Week 19660304',
 'Week 19660311',
 'Week 19660318',
 'Week 19660325',
 'Week 19660401',
 'Week 19660408',
 'Week 19660415',
 'Week 19660422',
 'Week 19660429',
 'Week 19660506',
 'Week 19660513',
 'Week 19660520',
 'Week 19660527',
 'Week 19660603',
 'Week 19660610',
 'Week 19660617',
 'Week 19660624',
 'Week 19660701',
 'Week 19660708',
 'Week 19660715',
 'Week 19660722',
 'Week 19660729',
 'Week 19660805',
 'Week 19660812',
 'Week 19660819',
 'Week 19660826',
 'Week 19660902',
 'Week 19660909',
 'Week 19660916',
 'Week 19660923',
 'Week 19660930',
 'Week 19661007',
 'Week 19661014',
 'Week 19661021',
 'Week 19661028',
 'Week 19661104',
 'Week 19661111',
 'Week 19661118',
 'Week 19661125',
 'Week 19661202',
 'Week 19661209',
 'Week 19661216',
 'Week 19661223',
 'Week 19661230',
 'Week 19670106',
 'Week 19670113',
 'Week 19670120',
 'Week 19670127',
 'Week 19670203',
 'Week 19670210',
 'Week 19670217',
 'Week 19670224',
 'Week 19670303',
 'Week 19670310',
 'Week 19670317',
 'Week 19670324',
 'Week 19670331',
 'Week 19670407',
 'Week 19670414',
 'Week 19670421',
 'Week 19670428',
 'Week 19670505',
 'Week 19670512',
 'Week 19670519',
 'Week 19670526',
 'Week 19670602',
 'Week 19670609',
 'Week 19670616',
 'Week 19670623',
 'Week 19670630',
 'Week 19670707',
 'Week 19670714',
 'Week 19670721',
 'Week 19670728',
 'Week 19670804',
 'Week 19670811',
 'Week 19670818',
 'Week 19670825',
 'Week 19670901',
 'Week 19670908',
 'Week 19670915',
 'Week 19670922',
 'Week 19670929',
 'Week 19671006',
 'Week 19671013',
 'Week 19671020',
 'Week 19671027',
 'Week 19671103',
 'Week 19671110',
 'Week 19671117',
 'Week 19671124',
 'Week 19671201',
 'Week 19671208',
 'Week 19671215',
 'Week 19671222',
 'Week 19671229',
 'Week 19680105',
 'Week 19680112',
 'Week 19680119',
 'Week 19680126',
 'Week 19680202',
 'Week 19680209',
 'Week 19680216',
 'Week 19680223',
 'Week 19680301',
 'Week 19680308',
 'Week 19680315',
 'Week 19680322',
 'Week 19680329',
 'Week 19680405',
 'Week 19680412',
 'Week 19680419',
 'Week 19680426',
 'Week 19680503',
 'Week 19680510',
 'Week 19680517',
 'Week 19680524',
 'Week 19680531',
 'Week 19680607',
 'Week 19680614',
 'Week 19680621',
 'Week 19680628',
 'Week 19680705',
 'Week 19680712',
 'Week 19680719',
 'Week 19680726',
 'Week 19680802',
 'Week 19680809',
 'Week 19680816',
 'Week 19680823',
 'Week 19680830',
 'Week 19680906',
 'Week 19680913',
 'Week 19680920',
 'Week 19680927',
 'Week 19681004',
 'Week 19681011',
 'Week 19681018',
 'Week 19681025',
 'Week 19681101',
 'Week 19681108',
 'Week 19681115',
 'Week 19681122',
 'Week 19681129',
 'Week 19681206',
 'Week 19681213',
 'Week 19681220',
 'Week 19681227',
 'Week 19690103',
 'Week 19690110',
 'Week 19690117',
 'Week 19690124',
 'Week 19690131',
 'Week 19690207',
 'Week 19690214',
 'Week 19690221',
 'Week 19690228',
 'Week 19690307',
 'Week 19690314',
 'Week 19690321',
 'Week 19690328',
 'Week 19690404',
 'Week 19690411',
 'Week 19690418',
 'Week 19690425',
 'Week 19690502',
 'Week 19690509',
 'Week 19690516',
 'Week 19690523',
 'Week 19690530',
 'Week 19690606',
 'Week 19690613',
 'Week 19690620',
 'Week 19690627',
 'Week 19690704',
 'Week 19690711',
 'Week 19690718',
 'Week 19690725',
 'Week 19690801',
 'Week 19690808',
 'Week 19690815',
 'Week 19690822',
 'Week 19690829',
 'Week 19690905',
 'Week 19690912',
 'Week 19690919',
 'Week 19690926',
 'Week 19691003',
 'Week 19691010',
 'Week 19691017',
 'Week 19691024',
 'Week 19691031',
 'Week 19691107',
 'Week 19691114',
 'Week 19691121',
 'Week 19691128',
 'Week 19691205',
 'Week 19691212',
 'Week 19691219',
 'Week 19691226',
 'Week 19700102',
 'Week 19700109',
 'Week 19700116',
 'Week 19700123',
 'Week 19700130',
 'Week 19700206',
 'Week 19700213',
 'Week 19700220',
 'Week 19700227',
 'Week 19700306',
 'Week 19700313',
 'Week 19700320',
 'Week 19700327',
 'Week 19700403',
 'Week 19700410',
 'Week 19700417',
 'Week 19700424',
 'Week 19700501',
 'Week 19700508',
 'Week 19700515',
 'Week 19700522',
 'Week 19700529',
 'Week 19700605',
 'Week 19700612',
 'Week 19700619',
 'Week 19700626',
 'Week 19700703',
 'Week 19700710',
 'Week 19700717',
 'Week 19700724',
 'Week 19700731',
 'Week 19700807',
 'Week 19700814',
 'Week 19700821',
 'Week 19700828',
 'Week 19700904',
 'Week 19700911',
 'Week 19700918',
 'Week 19700925',
 'Week 19701002',
 'Week 19701009',
 'Week 19701016',
 'Week 19701023',
 'Week 19701030',
 'Week 19701106',
 'Week 19701113',
 'Week 19701120',
 'Week 19701127',
 'Week 19701204',
 'Week 19701211',
 'Week 19701218',
 'Week 19701225',
 'Week 19710101',
 'Week 19710108',
 'Week 19710115',
 'Week 19710122',
 'Week 19710129',
 'Week 19710205',
 'Week 19710212',
 'Week 19710219',
 'Week 19710226',
 'Week 19710305',
 'Week 19710312',
 'Week 19710319',
 'Week 19710326',
 'Week 19710402',
 'Week 19710409',
 'Week 19710416',
 'Week 19710423',
 'Week 19710430',
 'Week 19710507',
 'Week 19710514',
 'Week 19710521',
 'Week 19710528',
 'Week 19710604',
 'Week 19710611',
 'Week 19710618',
 'Week 19710625',
 'Week 19710702',
 'Week 19710709',
 'Week 19710716',
 'Week 19710723',
 'Week 19710730',
 'Week 19710806',
 'Week 19710813',
 'Week 19710820',
 'Week 19710827',
 'Week 19710903',
 'Week 19710910',
 'Week 19710917',
 'Week 19710924',
 'Week 19711001',
 'Week 19711008',
 'Week 19711015',
 'Week 19711022',
 'Week 19711029',
 'Week 19711105',
 'Week 19711112',
 'Week 19711119',
 'Week 19711126',
 'Week 19711203',
 'Week 19711210',
 'Week 19711217',
 'Week 19711224',
 'Week 19711231',
 'Week 19720107',
 ...]

In [9]:
len(excel.sheet_names)

3725

In [10]:
excel.sheet_names[0]

'Week 19521114'

In [11]:
excel.sheet_names[-1]

'Week 20240329'

In [16]:
first_week = pd.read_excel(
    chart_file,
    sheet_name=excel.sheet_names[0]
)

first_week.head(15)

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
0,HE IN MY HEART,AL MARTINO,1,NaN,1,1,14 November 1952- 20 November 1952
1,YOU BELONG TO ME,JO STAFFORD,2,NaN,2,1,14 November 1952- 20 November 1952
2,SOMEWHE ALONG THE WAY,NAT 'KING' COLE,3,NaN,3,1,14 November 1952- 20 November 1952
3,THE ISLE OF INNISFE,BING CROSBY,4,NaN,4,1,14 November 1952- 20 November 1952
4,FEET UP (PAT HIM ON THE PO-PO),GUY MITCHELL,5,NaN,5,1,14 November 1952- 20 November 1952
5,HALF AS MUCH,ROSEMARY CLOONEY,6,NaN,6,1,14 November 1952- 20 November 1952
6,HIGH NOON (DO NOT FORSAKE ME),FRANKIE LAINE,7,NaN,7,1,14 November 1952- 20 November 1952
7,HIGH NOON (DO NOT FORSAKE ME),FRANKIE LAINE,7,NaN,7,1,14 November 1952- 20 November 1952
8,BLUE TANGO,RAY MARTIN,8,NaN,8,1,14 November 1952- 20 November 1952
9,BLUE TANGO,RAY MARTIN,8,NaN,8,1,14 November 1952- 20 November 1952
10,THE HOMING WALTZ,VERA LYNN,9,NaN,9,1,14 November 1952- 20 November 1952
11,AUF WIEDERSEH'N SWEETHEART,VERA LYNN,10,NaN,10,1,14 November 1952- 20 November 1952
12,COWPUNCHER'S CANTATA,MAX BYGRAVES,11,NaN,11,1,14 November 1952- 20 November 1952
13,COWPUNCHER'S CANTATA,MAX BYGRAVES,11,NaN,11,1,14 November 1952- 20 November 1952
14,WALKIN' MY BABY BACK HOME,JOHNNIE RAY,12,NaN,12,1,14 November 1952- 20 November 1952

### First observations

- Weekly sheets have a consistent column structure.
- The first sheet contains duplicate rows for several chart positions.
- Needs further investigation before import.

In [15]:
first_week.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Song            15 non-null     str
 1   Artist          15 non-null     str
 2   Position        15 non-null     int64
 3   Last Week       0 non-null      float64
 4   Peak            15 non-null     int64
 5   Weeks on Chart  15 non-null     int64
 6   Week            15 non-null     str
dtypes: float64(1), int64(3), str(3)
memory usage: 972.0 bytes

In [14]:
first_week.columns

Index(['Song', 'Artist', 'Position', 'Last Week', 'Peak', 'Weeks on Chart',
       'Week'],
      dtype='str')

In [17]:
week_1983 = pd.read_excel(
    chart_file,
    sheet_name="Week 19830107"
)

week_1983.head(15)

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
0,SAVE YOUR LOVE,RENEE AND RENATO,1,LW:1,1,11,2 January 1983- 8 January 1983
1,YOU CAN'T HURRY LOVE,PHIL COLLINS,2,LW:6,2,6,2 January 1983- 8 January 1983
2,A WINTER'S TALE,DAVID ESSEX,3,LW:7,3,5,2 January 1983- 8 January 1983
3,BEST YEARS OF OUR LIVES,MODERN ROMANCE,4,LW:8,4,9,2 January 1983- 8 January 1983
4,OUR HOUSE,MADNESS,5,LW:5,5,7,2 January 1983- 8 January 1983
5,TIME (CLOCK OF THE HEART),CULTURE CLUB,6,LW:4,3,7,2 January 1983- 8 January 1983
6,THE SHAKIN' STEVENS EP,SHAKIN' STEVENS,7,LW:2,2,5,2 January 1983- 8 January 1983
7,ORVILLE'S SONG,KEITH HARRIS AND ORVILLE,8,LW:33,8,4,2 January 1983- 8 January 1983
8,PEACE ON EARTH/LITTLE DRUMMER BOY,DAVID BOWIE AND BING CROSBY,9,LW:3,3,7,2 January 1983- 8 January 1983
9,ALL THE LOVE IN THE WORLD,DIONNE WARWICK,10,LW:14,10,5,2 January 1983- 8 January 1983
10,BUFFALO GALS,MALCOLM MCLAREN AND THE WORLD'S FAMOUS SUPREME...,11,LW:18,11,6,2 January 1983- 8 January 1983
11,HYMN,ULTRAVOX,12,LW:16,12,7,2 January 1983- 8 January 1983
12,IF YOU CAN'T STAND THE HEAT,BUCKS FIZZ,13,LW:20,13,7,2 January 1983- 8 January 1983
13,YOUNG GUNS (GO FOR IT),WHAM!,14,LW:13,3,13,2 January 1983- 8 January 1983
14,BEAT SURNDER,THE JAM,15,LW:10,1,6,2 January 1983- 8 January 1983

In [18]:
week_1983.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Song            100 non-null    str
 1   Artist          100 non-null    str
 2   Position        100 non-null    int64
 3   Last Week       100 non-null    str
 4   Peak            100 non-null    int64
 5   Weeks on Chart  100 non-null    int64
 6   Week            100 non-null    str
dtypes: int64(3), str(4)
memory usage: 5.6 KB

In [19]:
week_1983.columns

Index(['Song', 'Artist', 'Position', 'Last Week', 'Peak', 'Weeks on Chart',
       'Week'],
      dtype='str')

In [20]:
selected_sheets = [
    sheet
    for sheet in excel.sheet_names
    if sheet >= "Week 19830107"
]

len(selected_sheets)

2152

In [21]:
selected_sheets[:5]

['Week 19830107',
 'Week 19830114',
 'Week 19830121',
 'Week 19830128',
 'Week 19830204']

In [22]:
selected_sheets[-5:]

['Week 20240301',
 'Week 20240308',
 'Week 20240315',
 'Week 20240322',
 'Week 20240329']

In [24]:
test_charts = []

for sheet in selected_sheets[:5]:
    week_df = excel.parse(sheet)

    test_charts.append(week_df)

In [25]:
len(test_charts)

5

In [26]:
type(test_charts[0])

pandas.DataFrame

In [28]:
weekly_charts = []

for sheet in selected_sheets:
    week_df = excel.parse(sheet)
    weekly_charts.append(week_df)

In [29]:
len(weekly_charts)

2152

In [30]:
chart_history = pd.concat(
    weekly_charts,
    ignore_index=True
)

In [31]:
chart_history.shape

(211479, 7)

## Initial Data Validation

After importing all weekly UK chart sheets (1983–2024), several validation checks were performed:

- Verified the number of imported weeks.
- Checked the consistency of column names.
- Compared the number of chart entries per week.

In [32]:
chart_history.groupby("Week").size().describe()

count    2146.000000
mean       98.545666
std         7.799529
min        74.000000
25%       100.000000
50%       100.000000
75%       100.000000
max       200.000000
dtype: float64

In [33]:
chart_history.groupby("Week").size().value_counts().sort_index()

74        2
75      140
76        2
99       21
100    1975
150       2
200       4
Name: count, dtype: int64

In [34]:
songs_per_week = chart_history.groupby("Week").size()

songs_per_week[songs_per_week > 100]

Week
1 January 1989- 7 January 1989      200
2 January 2005- 8 January 2005      200
26 December 1993- 1 January 1994    150
26 December 1999- 1 January 2000    200
26 December 2010- 1 January 2011    200
3 January 1993- 9 January 1993      150
dtype: int64

### Data validation findings

- Most weeks contain exactly 100 chart entries.
- 140 early weeks contain 75 entries (expected historical format).
- Six weeks around the New Year contain duplicated chart positions.
- These weeks require special handling before final analysis.

In [38]:
week_1993 =chart_history[chart_history["Week"] == "26 December 1993- 1 January 1994"]
week_1993.head(15)

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
49851,MR. BLOBBY,MR. BLOBBY,1,LW:1,1,5,26 December 1993- 1 January 1994
49852,BABE,TAKE THAT,2,LW:2,1,3,26 December 1993- 1 January 1994
49853,TWIST AND SHOUT FT JACK RADICS AND TAXI GANG,CHAKA DEMUS AND PLIERS FEATURING JACK RADICS A...,3,LW:3,3,3,26 December 1993- 1 January 1994
49854,FOR WHOM THE BELL TOLLS,THE BEE GEES,4,LW:4,4,6,26 December 1993- 1 January 1994
49855,IT'S ALRIGHT,EAST 17,5,LW:5,5,5,26 December 1993- 1 January 1994
49856,THE PERFECT YEAR,DINA CARROLL,6,LW:7,6,4,26 December 1993- 1 January 1994
49857,I'D DO ANYTHING FOR LOVE (BUT I WON'T DO THAT),MEAT LOAF,7,LW:6,1,13,26 December 1993- 1 January 1994
49858,BAT OUT OF HELL {1993},MEAT LOAF,8,LW:8,8,10,26 December 1993- 1 January 1994
49859,TRUE LOVE,ELTON JOHN AND KIKI DEE,9,LW:9,2,7,26 December 1993- 1 January 1994
49860,COME BABY COME,K7,10,LW:13,10,4,26 December 1993- 1 January 1994
49861,PLEASE FORGIVE ME,BRYAN ADAMS,11,LW:11,2,10,26 December 1993- 1 January 1994
49862,A WHOLE NEW WORLD (ALADDIN'S THEME),PEABO BRYSON AND REGINA BELLE,12,LW:12,12,4,26 December 1993- 1 January 1994
49863,THE POWER OF LOVE {1993},FRANKIE GOES TO HOLLYWOOD,13,LW:10,1,21,26 December 1993- 1 January 1994
49864,YOUR LOVE,DIANA ROSS,14,LW:17,14,4,26 December 1993- 1 January 1994
49865,HERO,MARIAH CAREY,15,LW:18,7,9,26 December 1993- 1 January 1994

In [39]:
display(week_1993.shape)
week_1993["Position"].value_counts().sort_index()

(150, 7)

Position
1     2
2     2
3     2
4     2
5     2
     ..
71    2
72    2
73    2
74    2
75    2
Name: count, Length: 75, dtype: int64