## Goal

Explore which chart statistics best describe the long-term chart performance of individual songs.

### Tasks

- Load cleaned chart history
- Explore song chart histories
- Identify meaningful chart metrics
- Test aggregation approaches
- Design the chart statistics table

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# Load Dataset

project_path = Path.cwd().parent
interim_path = project_path / 'data' / 'interim'

chart_history = pd.read_csv(interim_path/'uk_chart_history_clean.csv')

In [3]:
chart_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 210882 entries, 0 to 210881
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Song            210882 non-null  str
 1   Artist          210837 non-null  str
 2   Position        210882 non-null  int64
 3   Last Week       210882 non-null  str
 4   Peak            210882 non-null  int64
 5   Weeks on Chart  210882 non-null  int64
 6   Week            210882 non-null  str
dtypes: int64(3), str(4)
memory usage: 11.3 MB

## Explore Chart Histories

The purpose of this notebook is to identify meaningful statistics that describe the chart performance of individual songs.

Several candidate metrics will be explored before defining the final chart statistics table.

In [4]:
song_history = chart_history[
    (chart_history['Song'] == 'OUR HOUSE') &
    (chart_history['Artist'] == 'MADNESS')
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
4,OUR HOUSE,MADNESS,5,LW:5,5,7,2 January 1983- 8 January 1983
112,OUR HOUSE,MADNESS,13,LW:5,5,8,9 January 1983- 15 January 1983
208,OUR HOUSE,MADNESS,10,LW:13,5,9,16 January 1983- 22 January 1983
319,OUR HOUSE,MADNESS,21,LW:10,5,10,23 January 1983- 29 January 1983
433,OUR HOUSE,MADNESS,35,LW:21,5,11,30 January 1983- 5 February 1983
551,OUR HOUSE,MADNESS,53,LW:35,5,12,6 February 1983- 12 February 1983
671,OUR HOUSE,MADNESS,73,LW:53,5,13,13 February 1983- 19 February 1983
149375,OUR HOUSE,MADNESS,92,LW:RE,5,14,10 June 2012- 16 June 2012
150382,OUR HOUSE,MADNESS,99,LW:RE,5,15,19 August 2012- 25 August 2012

In [5]:
song_history = chart_history[
    (chart_history['Song'] == 'LAST CHRISTMAS') &
    (chart_history['Artist'] == 'WHAM!')
]

song_history

Empty DataFrame
Columns: [Song, Artist, Position, Last Week, Peak, Weeks on Chart, Week]
Index: []

In [6]:
song_history = chart_history[
    (chart_history['Song'] == 'BOHEMIAN RHAPSODY') &
    (chart_history['Artist'] == 'QUEEN')
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
136176,BOHEMIAN RHAPSODY,QUEEN,93,LW:RE,1,18,22 November 2009- 28 November 2009
182636,BOHEMIAN RHAPSODY,QUEEN,53,LW:RE,1,19,2 November 2018- 8 November 2018
182729,BOHEMIAN RHAPSODY,QUEEN,46,LW:53,1,20,9 November 2018- 15 November 2018
182828,BOHEMIAN RHAPSODY,QUEEN,45,LW:46,1,21,16 November 2018- 22 November 2018
182935,BOHEMIAN RHAPSODY,QUEEN,52,LW:45,1,22,23 November 2018- 29 November 2018
183033,BOHEMIAN RHAPSODY,QUEEN,50,LW:52,1,23,30 November 2018- 6 December 2018
183158,BOHEMIAN RHAPSODY,QUEEN,75,LW:50,1,24,7 December 2018- 13 December 2018
183269,BOHEMIAN RHAPSODY,QUEEN,86,LW:75,1,25,14 December 2018- 20 December 2018
183531,BOHEMIAN RHAPSODY,QUEEN,48,LW:RE,1,26,4 January 2019- 10 January 2019
183648,BOHEMIAN RHAPSODY,QUEEN,65,LW:48,1,27,11 January 2019- 17 January 2019
183751,BOHEMIAN RHAPSODY,QUEEN,68,LW:65,1,28,18 January 2019- 24 January 2019
183859,BOHEMIAN RHAPSODY,QUEEN,76,LW:68,1,29,25 January 2019- 31 January 2019
183965,BOHEMIAN RHAPSODY,QUEEN,82,LW:76,1,30,1 February 2019- 7 February 2019
184070,BOHEMIAN RHAPSODY,QUEEN,87,LW:82,1,31,8 February 2019- 14 February 2019
184164,BOHEMIAN RHAPSODY,QUEEN,81,LW:87,1,32,15 February 2019- 21 February 2019
184261,BOHEMIAN RHAPSODY,QUEEN,78,LW:81,1,33,22 February 2019- 28 February 2019
184354,BOHEMIAN RHAPSODY,QUEEN,71,LW:78,1,34,1 March 2019- 7 March 2019
184447,BOHEMIAN RHAPSODY,QUEEN,64,LW:71,1,35,8 March 2019- 14 March 2019
184545,BOHEMIAN RHAPSODY,QUEEN,62,LW:64,1,36,15 March 2019- 21 March 2019
184643,BOHEMIAN RHAPSODY,QUEEN,60,LW:62,1,37,22 March 2019- 28 March 2019
184747,BOHEMIAN RHAPSODY,QUEEN,64,LW:60,1,38,29 March 2019- 4 April 2019
184856,BOHEMIAN RHAPSODY,QUEEN,73,LW:64,1,39,5 April 2019- 11 April 2019
184959,BOHEMIAN RHAPSODY,QUEEN,76,LW:73,1,40,12 April 2019- 18 April 2019
185053,BOHEMIAN RHAPSODY,QUEEN,70,LW:76,1,41,19 April 2019- 25 April 2019
185164,BOHEMIAN RHAPSODY,QUEEN,81,LW:70,1,42,26 April 2019- 2 May 2019
185379,BOHEMIAN RHAPSODY,QUEEN,96,LW:RE,1,43,10 May 2019- 16 May 2019
185481,BOHEMIAN RHAPSODY,QUEEN,98,LW:96,1,44,17 May 2019- 23 May 2019
185678,BOHEMIAN RHAPSODY,QUEEN,95,LW:RE,1,45,31 May 2019- 6 June 2019
187375,BOHEMIAN RHAPSODY,QUEEN,92,LW:RE,1,46,27 September 2019- 3 October 2019
187475,BOHEMIAN RHAPSODY,QUEEN,92,LW:92,1,47,4 October 2019- 10 October 2019
201678,BOHEMIAN RHAPSODY,QUEEN,95,LW:RE,1,48,24 June 2022- 30 June 2022
201776,BOHEMIAN RHAPSODY,QUEEN,93,LW:95,1,49,1 July 2022- 7 July 2022
201880,BOHEMIAN RHAPSODY,QUEEN,97,LW:93,1,50,8 July 2022- 14 July 2022

In [7]:
song_history = chart_history[
    (chart_history['Song'] == 'RUNNING UP THAT HILL') &
    (chart_history['Artist'] == 'KATE BUSH')
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
13596,RUNNING UP THAT HILL,KATE BUSH,9,LW:New,9,1,11 August 1985- 17 August 1985
13691,RUNNING UP THAT HILL,KATE BUSH,4,LW:9,4,2,18 August 1985- 24 August 1985
13789,RUNNING UP THAT HILL,KATE BUSH,3,LW:4,3,3,25 August 1985- 31 August 1985
13891,RUNNING UP THAT HILL,KATE BUSH,5,LW:3,3,4,1 September 1985- 7 September 1985
13994,RUNNING UP THAT HILL,KATE BUSH,8,LW:5,3,5,8 September 1985- 14 September 1985
14101,RUNNING UP THAT HILL,KATE BUSH,15,LW:8,3,6,15 September 1985- 21 September 1985
14209,RUNNING UP THAT HILL,KATE BUSH,23,LW:15,3,7,22 September 1985- 28 September 1985
14319,RUNNING UP THAT HILL,KATE BUSH,33,LW:23,3,8,29 September 1985- 5 October 1985
14435,RUNNING UP THAT HILL,KATE BUSH,49,LW:33,3,9,6 October 1985- 12 October 1985
14547,RUNNING UP THAT HILL,KATE BUSH,61,LW:49,3,10,13 October 1985- 19 October 1985
14661,RUNNING UP THAT HILL,KATE BUSH,75,LW:61,3,11,20 October 1985- 26 October 1985
148934,RUNNING UP THAT HILL,KATE BUSH,51,LW:RE,3,12,13 May 2012- 19 May 2012
150289,RUNNING UP THAT HILL,KATE BUSH,6,LW:RE,3,13,19 August 2012- 25 August 2012
150416,RUNNING UP THAT HILL,KATE BUSH,33,LW:6,3,14,26 August 2012- 1 September 2012
150546,RUNNING UP THAT HILL,KATE BUSH,63,LW:33,3,15,2 September 2012- 8 September 2012
160934,RUNNING UP THAT HILL,KATE BUSH,51,LW:RE,3,16,31 August 2014- 6 September 2014
161081,RUNNING UP THAT HILL,KATE BUSH,98,LW:51,3,17,7 September 2014- 13 September 2014
201291,RUNNING UP THAT HILL,KATE BUSH,8,LW:RE,3,18,3 June 2022- 9 June 2022
201385,RUNNING UP THAT HILL,KATE BUSH,2,LW:8,2,19,10 June 2022- 16 June 2022
201484,RUNNING UP THAT HILL,KATE BUSH,1,LW:2,1,20,17 June 2022- 23 June 2022
201584,RUNNING UP THAT HILL,KATE BUSH,1,LW:1,1,21,24 June 2022- 30 June 2022
201684,RUNNING UP THAT HILL,KATE BUSH,1,LW:1,1,22,1 July 2022- 7 July 2022
201786,RUNNING UP THAT HILL,KATE BUSH,3,LW:1,1,23,8 July 2022- 14 July 2022
201888,RUNNING UP THAT HILL,KATE BUSH,5,LW:3,1,24,15 July 2022- 21 July 2022
201991,RUNNING UP THAT HILL,KATE BUSH,8,LW:5,1,25,22 July 2022- 28 July 2022
202092,RUNNING UP THAT HILL,KATE BUSH,9,LW:8,1,26,29 July 2022- 4 August 2022
202192,RUNNING UP THAT HILL,KATE BUSH,9,LW:9,1,27,5 August 2022- 11 August 2022
202297,RUNNING UP THAT HILL,KATE BUSH,14,LW:9,1,28,12 August 2022- 18 August 2022
202402,RUNNING UP THAT HILL,KATE BUSH,19,LW:14,1,29,19 August 2022- 25 August 2022
202503,RUNNING UP THAT HILL,KATE BUSH,20,LW:19,1,30,26 August 2022- 1 September 2022
202606,RUNNING UP THAT HILL,KATE BUSH,23,LW:20,1,31,2 September 2022- 8 September 2022
202705,RUNNING UP THAT HILL,KATE BUSH,22,LW:23,1,32,9 September 2022- 15 September 2022
202808,RUNNING UP THAT HILL,KATE BUSH,25,LW:22,1,33,16 September 2022- 22 September 2022
202913,RUNNING UP THAT HILL,KATE BUSH,30,LW:25,1,34,23 September 2022- 29 September 2022
203015,RUNNING UP THAT HILL,KATE BUSH,32,LW:30,1,35,30 September 2022- 6 October 2022
203117,RUNNING UP THAT HILL,KATE BUSH,34,LW:32,1,36,7 October 2022- 13 October 2022
203218,RUNNING UP THAT HILL,KATE BUSH,35,LW:34,1,37,14 October 2022- 20 October 2022
203335,RUNNING UP THAT HILL,KATE BUSH,52,LW:35,1,38,21 October 2022- 27 October 2022
203431,RUNNING UP THAT HILL,KATE BUSH,48,LW:52,1,39,28 October 2022- 3 November 2022
203527,RUNNING UP THAT HILL,KATE BUSH,44,LW:48,1,40,4 November 2022- 10 November 2022
203638,RUNNING UP THAT HILL,KATE BUSH,55,LW:44,1,41,11 November 2022- 17 November 2022
203743,RUNNING UP THAT HILL,KATE BUSH,60,LW:55,1,42,18 November 2022- 24 November 2022
203850,RUNNING UP THAT HILL,KATE BUSH,67,LW:60,1,43,25 November 2022- 1 December 2022
203965,RUNNING UP THAT HILL,KATE BUSH,82,LW:67,1,44,2 December 2022- 8 December 2022
204081,RUNNING UP THAT HILL,KATE BUSH,98,LW:82,1,45,9 December 2022- 15 December 2022
204438,RUNNING UP THAT HILL,KATE BUSH,55,LW:RE,1,46,6 January 2023- 12 January 2023
204560,RUNNING UP THAT HILL,KATE BUSH,77,LW:55,1,47,13 January 2023- 19 January 2023
204671,RUNNING UP THAT HILL,KATE BUSH,88,LW:77,1,48,20 January 2023- 26 January 2023
204773,RUNNING UP THAT HILL,KATE BUSH,90,LW:88,1,49,27 January 2023- 2 February 2023
204874,RUNNING UP THAT HILL,KATE BUSH,91,LW:90,1,50,3 February 2023- 9 February 2023
204969,RUNNING UP THAT HILL,KATE BUSH,86,LW:91,1,51,10 February 2023- 16 February 2023
205381,RUNNING UP THAT HILL,KATE BUSH,98,LW:RE,1,52,10 March 2023- 16 March 2023

In [8]:
song_history = chart_history[
    (chart_history['Song'] == 'NEVER GONNA GIVE YOU UP') &
    (chart_history['Artist'] == 'RICK ASTLEY')
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
20862,NEVER GONNA GIVE YOU UP,RICK ASTLEY,85,LW:91,1,21,27 December 1987- 2 January 1988
23899,NEVER GONNA GIVE YOU UP,RICK ASTLEY,32,LW:New,32,1,2 August 1987- 8 August 1987
23981,NEVER GONNA GIVE YOU UP,RICK ASTLEY,14,LW:32,14,2,9 August 1987- 15 August 1987
24070,NEVER GONNA GIVE YOU UP,RICK ASTLEY,3,LW:14,3,3,16 August 1987- 22 August 1987
24168,NEVER GONNA GIVE YOU UP,RICK ASTLEY,1,LW:3,1,4,23 August 1987- 29 August 1987
24267,NEVER GONNA GIVE YOU UP,RICK ASTLEY,1,LW:1,1,5,30 August 1987- 5 September 1987
24367,NEVER GONNA GIVE YOU UP,RICK ASTLEY,1,LW:1,1,6,6 September 1987- 12 September 1987
24467,NEVER GONNA GIVE YOU UP,RICK ASTLEY,1,LW:1,1,7,13 September 1987- 19 September 1987
24566,NEVER GONNA GIVE YOU UP,RICK ASTLEY,1,LW:1,1,8,20 September 1987- 26 September 1987
24667,NEVER GONNA GIVE YOU UP,RICK ASTLEY,2,LW:1,1,9,27 September 1987- 3 October 1987
24769,NEVER GONNA GIVE YOU UP,RICK ASTLEY,4,LW:2,1,10,4 October 1987- 10 October 1987
24875,NEVER GONNA GIVE YOU UP,RICK ASTLEY,10,LW:4,1,11,11 October 1987- 17 October 1987
24987,NEVER GONNA GIVE YOU UP,RICK ASTLEY,22,LW:10,1,12,18 October 1987- 24 October 1987
25093,NEVER GONNA GIVE YOU UP,RICK ASTLEY,28,LW:22,1,13,25 October 1987- 31 October 1987
25202,NEVER GONNA GIVE YOU UP,RICK ASTLEY,37,LW:28,1,14,1 November 1987- 7 November 1987
25310,NEVER GONNA GIVE YOU UP,RICK ASTLEY,45,LW:37,1,15,8 November 1987- 14 November 1987
25405,NEVER GONNA GIVE YOU UP,RICK ASTLEY,40,LW:45,1,16,15 November 1987- 21 November 1987
25512,NEVER GONNA GIVE YOU UP,RICK ASTLEY,47,LW:40,1,17,22 November 1987- 28 November 1987
25628,NEVER GONNA GIVE YOU UP,RICK ASTLEY,64,LW:47,1,18,29 November 1987- 5 December 1987
25853,NEVER GONNA GIVE YOU UP,RICK ASTLEY,90,LW:RE,1,19,13 December 1987- 19 December 1987
25954,NEVER GONNA GIVE YOU UP,RICK ASTLEY,91,LW:90,1,20,20 December 1987- 26 December 1987
26146,NEVER GONNA GIVE YOU UP,RICK ASTLEY,83,LW:85,1,22,3 January 1988- 9 January 1988
131356,NEVER GONNA GIVE YOU UP,RICK ASTLEY,73,LW:RE,1,23,21 December 2008- 27 December 2008

In [9]:
song_history = chart_history[
    (chart_history['Song'] == 'MR BRIGHTSIDE') &
    (chart_history['Artist'] == 'THE KILLERS')
]

song_history

Empty DataFrame
Columns: [Song, Artist, Position, Last Week, Peak, Weeks on Chart, Week]
Index: []

In [10]:
song_history = chart_history[
    chart_history['Song'] == 'BARBIE GIRL'
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
73193,BARBIE GIRL,AQUA,2,LW:New,2,1,19 October 1997- 25 October 1997
73292,BARBIE GIRL,AQUA,1,LW:2,1,2,26 October 1997- 1 November 1997
73392,BARBIE GIRL,AQUA,1,LW:1,1,3,2 November 1997- 8 November 1997
73492,BARBIE GIRL,AQUA,1,LW:1,1,4,9 November 1997- 15 November 1997
73592,BARBIE GIRL,AQUA,1,LW:1,1,5,16 November 1997- 22 November 1997
73693,BARBIE GIRL,AQUA,2,LW:1,1,6,23 November 1997- 29 November 1997
73794,BARBIE GIRL,AQUA,3,LW:2,1,7,30 November 1997- 6 December 1997
73894,BARBIE GIRL,AQUA,3,LW:3,1,8,7 December 1997- 13 December 1997
73994,BARBIE GIRL,AQUA,3,LW:3,1,9,14 December 1997- 20 December 1997
74097,BARBIE GIRL,AQUA,6,LW:3,1,10,21 December 1997- 27 December 1997
74301,BARBIE GIRL,AQUA,10,LW:7,1,12,4 January 1998- 10 January 1998
74409,BARBIE GIRL,AQUA,18,LW:10,1,13,11 January 1998- 17 January 1998
74515,BARBIE GIRL,AQUA,24,LW:18,1,14,18 January 1998- 24 January 1998
74622,BARBIE GIRL,AQUA,31,LW:24,1,15,25 January 1998- 31 January 1998
74725,BARBIE GIRL,AQUA,34,LW:31,1,16,1 February 1998- 7 February 1998
74827,BARBIE GIRL,AQUA,36,LW:34,1,17,8 February 1998- 14 February 1998
74930,BARBIE GIRL,AQUA,39,LW:36,1,18,15 February 1998- 21 February 1998
75036,BARBIE GIRL,AQUA,45,LW:39,1,19,22 February 1998- 28 February 1998
75147,BARBIE GIRL,AQUA,57,LW:45,1,20,1 March 1998- 7 March 1998
75249,BARBIE GIRL,AQUA,60,LW:57,1,21,8 March 1998- 14 March 1998
75346,BARBIE GIRL,AQUA,58,LW:60,1,22,15 March 1998- 21 March 1998
75451,BARBIE GIRL,AQUA,63,LW:58,1,23,22 March 1998- 28 March 1998
75558,BARBIE GIRL,AQUA,70,LW:63,1,24,29 March 1998- 4 April 1998
75771,BARBIE GIRL,AQUA,83,LW:RE,1,25,12 April 1998- 18 April 1998
75854,BARBIE GIRL,AQUA,66,LW:83,1,26,19 April 1998- 25 April 1998
75961,BARBIE GIRL,AQUA,73,LW:66,1,27,26 April 1998- 2 May 1998
125109,BARBIE GIRL,SAMANDA,26,LW:New,26,1,14 October 2007- 20 October 2007
125218,BARBIE GIRL,SAMANDA,35,LW:26,26,2,21 October 2007- 27 October 2007
125340,BARBIE GIRL,SAMANDA,57,LW:35,26,3,28 October 2007- 3 November 2007
125463,BARBIE GIRL,SAMANDA,80,LW:57,26,4,4 November 2007- 10 November 2007
125573,BARBIE GIRL,SAMANDA,90,LW:80,26,5,11 November 2007- 17 November 2007
207323,BARBIE GIRL,AQUA,40,LW:RE,1,28,28 July 2023- 3 August 2023
207425,BARBIE GIRL,AQUA,42,LW:40,1,29,4 August 2023- 10 August 2023
207532,BARBIE GIRL,AQUA,50,LW:42,1,30,11 August 2023- 17 August 2023
207638,BARBIE GIRL,AQUA,57,LW:50,1,31,18 August 2023- 24 August 2023

In [11]:
song_history = chart_history[
    chart_history['Song'] == 'BLUE (DA BA DEE)'
]

song_history

,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
79416,BLUE (DA BA DEE),EIFFEL 65,28,LW:36,1,15,26 December 1999- 1 January 2000
82746,BLUE (DA BA DEE),EIFFEL 65,61,LW:New,61,1,15 August 1999- 21 August 1999
82848,BLUE (DA BA DEE),EIFFEL 65,63,LW:61,61,2,22 August 1999- 28 August 1999
82935,BLUE (DA BA DEE),EIFFEL 65,51,LW:63,51,3,29 August 1999- 4 September 1999
83023,BLUE (DA BA DEE),EIFFEL 65,39,LW:51,39,4,5 September 1999- 11 September 1999
83127,BLUE (DA BA DEE),EIFFEL 65,43,LW:39,39,5,12 September 1999- 18 September 1999
83184,BLUE (DA BA DEE),EIFFEL 65,1,LW:New,1,1,19 September 1999- 25 September 1999
83284,BLUE (DA BA DEE),EIFFEL 65,1,LW:1,1,2,26 September 1999- 2 October 1999
83384,BLUE (DA BA DEE),EIFFEL 65,1,LW:1,1,3,3 October 1999- 9 October 1999
83486,BLUE (DA BA DEE),EIFFEL 65,3,LW:1,1,4,10 October 1999- 16 October 1999
83587,BLUE (DA BA DEE),EIFFEL 65,4,LW:3,1,5,17 October 1999- 23 October 1999
83689,BLUE (DA BA DEE),EIFFEL 65,6,LW:4,1,6,24 October 1999- 30 October 1999
83791,BLUE (DA BA DEE),EIFFEL 65,8,LW:6,1,7,31 October 1999- 6 November 1999
83895,BLUE (DA BA DEE),EIFFEL 65,12,LW:8,1,8,7 November 1999- 13 November 1999
84001,BLUE (DA BA DEE),EIFFEL 65,18,LW:12,1,9,14 November 1999- 20 November 1999
84104,BLUE (DA BA DEE),EIFFEL 65,21,LW:18,1,10,21 November 1999- 27 November 1999
84204,BLUE (DA BA DEE),EIFFEL 65,21,LW:21,1,11,28 November 1999- 4 December 1999
84313,BLUE (DA BA DEE),EIFFEL 65,30,LW:21,1,12,5 December 1999- 11 December 1999
84413,BLUE (DA BA DEE),EIFFEL 65,30,LW:30,1,13,12 December 1999- 18 December 1999
84519,BLUE (DA BA DEE),EIFFEL 65,36,LW:30,1,14,19 December 1999- 25 December 1999
84612,BLUE (DA BA DEE),EIFFEL 65,29,LW:28,1,16,2 January 2000- 8 January 2000
84717,BLUE (DA BA DEE),EIFFEL 65,34,LW:29,1,17,9 January 2000- 15 January 2000
84824,BLUE (DA BA DEE),EIFFEL 65,41,LW:34,1,18,16 January 2000- 22 January 2000
84934,BLUE (DA BA DEE),EIFFEL 65,51,LW:41,1,19,23 January 2000- 29 January 2000
85051,BLUE (DA BA DEE),EIFFEL 65,68,LW:51,1,20,30 January 2000- 5 February 2000
85155,BLUE (DA BA DEE),EIFFEL 65,72,LW:68,1,21,6 February 2000- 12 February 2000
85259,BLUE (DA BA DEE),EIFFEL 65,76,LW:72,1,22,13 February 2000- 19 February 2000
85474,BLUE (DA BA DEE),EIFFEL 65,91,LW:RE,1,23,27 February 2000- 4 March 2000
85579,BLUE (DA BA DEE),EIFFEL 65,96,LW:91,1,24,5 March 2000- 11 March 2000
85678,BLUE (DA BA DEE),EIFFEL 65,95,LW:96,1,25,12 March 2000- 18 March 2000
85782,BLUE (DA BA DEE),EIFFEL 65,99,LW:95,1,26,19 March 2000- 25 March 2000